# Generated by Django 3.2.5 on 2021-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droid_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_bot_chats',
            name='button_dumb',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='telegram_bot_chats',
            name='button_fat',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='telegram_bot_chats',
            name='button_stupid',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
